version: 2.1
jobs:
  build:
    working_directory: ~/sunbird-player-sdk
    docker:
      - image: circleci/node:12.13.0
    steps:
      - checkout:
          path: ~/sunbird-player-sdk

      - run: cd projects/sunbird-player-sdk && npm install
      - run: npm install
      - run:
          name: Installing angular cli
          command: 'npm install @angular/cli@6.0.8 --no-progress'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - save_cache: # special step to save the dependency cache	
          key: dependency-cache-{{ checksum "package.json" }}	
          paths: ./node_modules    
      - run:
          name: Executing test cases
          command: 'npm run test | tee /tmp/logs/test_cases.log'
      - run: 
          name: Install sonar scanner
          command: 'npm install -g sonarqube-scanner'
          
      - run: 
          name: Sonar scanner
          command: sonar-scanner -Dsonar.projectKey=project-sunbird_sunbird-player-sdk -Dsonar.organization=project-sunbird -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.language=ts -Dsonar.sources=projects/sunbird-player-sdk/src -Dsonar.typescript.lcov.reportPaths=coverage/sunbird-player-sdk/lcov.info
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
